agent_name = "daily-diary-agent"
image = "tomoima525/daily-diary-agent:0.2"
secret_set = "daily-diary-agent-secrets"
enable_krisp = true
image_credentials = "tomo-image-pull-secret"

[scaling]
	min_agents = 0
	max_agents = 3
